//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebMessageStoreSoap", Namespace="http://www.cross-platform.net/GuestBook/")]
public class WebMessageStoreProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public WebMessageStoreProxy() {
        this.Url = "http://192.168.0.3/WebMessageStore.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cross-platform.net/GuestBook/GetMessages", RequestNamespace="http://www.cross-platform.net/GuestBook/", ResponseNamespace="http://www.cross-platform.net/GuestBook/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetMessages() {
        object[] results = this.Invoke("GetMessages", new object[0]);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetMessages(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetMessages", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetMessages(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
}
